"""add procurando_jogadores to clubes

Revision ID: 1dea114cbe5e
Revises: ccfae0615414
Create Date: 2025-05-31 19:34:55.465080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dea114cbe5e'
down_revision: Union[str, None] = 'ccfae0615414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubes', sa.Column('procurando_jogadores', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubes', 'procurando_jogadores')
    # ### end Alembic commands ###
