"""add clube_id to usuarios

Revision ID: ccfae0615414
Revises: 
Create Date: 2025-05-31 19:26:09.965838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfae0615414'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('clube_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'clubes', ['clube_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'clube_id')
    # ### end Alembic commands ###
