"""make clube_id nullable

Revision ID: e8f21ec8f2b5
Revises: 1dea114cbe5e
Create Date: 2025-05-31 20:02:38.998170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f21ec8f2b5'
down_revision: Union[str, None] = '1dea114cbe5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
